server:
  port: 5000

spring:
  application:
    name: products-backend
  threads:
    virtual:
      enabled: true

upstream:
  base-url: http://localhost:3001
  connect-timeout: 2s
  response-timeout: 6s
  max-connections: 1000
  max-connections-per-route: 1000

logging:
  level:
    com.inditex.core: INFO